return {
	["."] = "cd",
	["<2-LeftMouse>"] = "edit",
	["<bs>"] = "close_node",
	["<cr>"] = "edit",
	["F"] = "clear_live_filter",
	["H"] = "toggle_dotfiles",
	["K"] = "toggle_file_info",
	["R"] = "full_rename",
	["Z"] = "expand_all",
	["a"] = "create",
	["d"] = "remove",
	["f"] = "live_filter",
	["h"] = "close_node",
	["l"] = "edit",
	["p"] = "paste",
	["q"] = "close",
	["r"] = "rename",
	["x"] = "cut",
	["y"] = "copy",
	["z"] = "collapse_all",
}
